var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/blog/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__23913dd4._.js")
R.c("server/chunks/ssr/beeckle-website_9fef1113._.js")
R.c("server/chunks/ssr/beeckle-website_f1fa994b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__2d26109f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__28814e6e._.js")
R.c("server/chunks/ssr/846f5_next_dist_28a3088b._.js")
R.c("server/chunks/ssr/beeckle-website_src_app_426fb134._.js")
R.c("server/chunks/ssr/846f5_next_dist_client_components_builtin_global-error_b853164c.js")
R.c("server/chunks/ssr/[root-of-the-server]__a8060963._.js")
R.c("server/chunks/ssr/beeckle-website_src_components_ui_button_tsx_283f9b50._.js")
R.c("server/chunks/ssr/846f5_next_dist_client_components_4911bc83._.js")
R.c("server/chunks/ssr/846f5_next_dist_client_components_builtin_forbidden_fc080760.js")
R.c("server/chunks/ssr/846f5_next_dist_client_components_builtin_unauthorized_224e4e74.js")
R.c("server/chunks/ssr/beeckle-website_src_app_admin_layout_tsx_9bb1ac10._.js")
R.c("server/chunks/ssr/beeckle-website__next-internal_server_app_admin_blog_page_actions_5b028046.js")
R.m(48941)
module.exports=R.m(48941).exports
